/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as CommunitiesSlugRouteImport } from './routes/communities.$slug'
import { Route as CommunitiesNewRouteImport } from './routes/communities.new'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/communities/$slug',
  path: '/communities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesNewRoute = CommunitiesNewRouteImport.update({
  id: '/communities/new',
  path: '/communities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/moderation': typeof ModerationRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/u/$username': typeof UUsernameRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/moderation': typeof ModerationRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/u/$username': typeof UUsernameRoute
  '/communities': typeof CommunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/moderation': typeof ModerationRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/u/$username': typeof UUsernameRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/moderation'
    | '/onboarding'
    | '/settings'
    | '/communities/$slug'
    | '/communities/new'
    | '/u/$username'
    | '/communities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/moderation'
    | '/onboarding'
    | '/settings'
    | '/communities/$slug'
    | '/communities/new'
    | '/u/$username'
    | '/communities'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/moderation'
    | '/onboarding'
    | '/settings'
    | '/communities/$slug'
    | '/communities/new'
    | '/u/$username'
    | '/communities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  ModerationRoute: typeof ModerationRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
  CommunitiesNewRoute: typeof CommunitiesNewRoute
  UUsernameRoute: typeof UUsernameRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$slug': {
      id: '/communities/$slug'
      path: '/communities/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/new': {
      id: '/communities/new'
      path: '/communities/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof CommunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  ModerationRoute: ModerationRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  CommunitiesSlugRoute: CommunitiesSlugRoute,
  CommunitiesNewRoute: CommunitiesNewRoute,
  UUsernameRoute: UUsernameRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
